### ISSUE TITLE
bug with GraphicSupport and multiple components with the same selection

### ISSUE THREAD

**Issue by wolfbiter** [lightblade/ember-cli-d3#40] opened 2015-12-27 20:59 UTC
So i've been playing with ember-cli-d3 v1.1.2

**Overview** i'm trying to do some complex rendering, using `each` loops inside a data visual. see this code, noting that `arrangement-grid` extends `data-visual` and yields `stg.svg.select`:

```

{{#arrangement-grid
  arrangement=arrangement
  isReady=isReady
  pxPerBeat=pxPerBeat
  scrollCenterBeat=scrollCenterBeat
  seekToBeat="seekToBeat"
  as |select height width|
}}
    {{#each mix.items as |item|}}
      {{arrangement-grid/track-clip
        select=select
        clip=item.fromTrackClip
        pxPerBeat=pxPerBeat
      }}

      {{#if item.isLastItem}}
        {{arrangement-grid/track-clip
          select=select
          clip=item.toTrackClip
          pxPerBeat=pxPerBeat
        }}
      {{/if}}
    {{/each}}
{{/arrangement-grid}}
```

**Problem**: `call` is only called for the last `track-clip` rendered in the each loop! i traced this down to be a bug with `GraphicSupport.didReceiveAttrs`, where `scheduleOnce` was overriding previous schedulings for the same selection (but DIFFERENT components). i fixed this locally, and am open to discussion on what you think of this approach

broken version:

```
  didReceiveAttrs() {
    this._super(...arguments);
    var selection = this.get('select');

    if (selection && !this.isDestroying && this.get('requiredProperties').map(prop => Boolean(!!this.get(prop))).reduce(((prev, cur) => prev && cur), true)) {
        // THIS LINE is overriding previous schedules, since `selection` is the same but `component` is different!
        Ember.run.scheduleOnce('afterRender', selection, selection.call, this);
    }
  }
});
```

fixt version:

```
  didReceiveAttrs() {
    this._super(...arguments);
    var selection = this.get('select');

    if (selection && !this.isDestroying && this.get('requiredProperties').map(prop => Boolean(!!this.get(prop))).reduce(((prev, cur) => prev && cur), true)) {
        // THIS LINE fixed by setting context to the component, so runOnce for each component
      Ember.run.scheduleOnce('afterRender', this, () => {
        selection.call(this);
      });
    }
  }
});
```

**Comment by wolfbiter** [comment] 2015-12-27 21:04
my use-case here: i want scope each `track-clip` component to be its own 'g', where the component itself provides the class and id (using `track-clip.elementId`). then inside each `track-clip` component we have a `track-clip/wave` and `track-clip/axis`, which use this particular `track-clip`'s selection

if you have ideas for alternative approach, i'm all ears

**Comment by ming-codes** [comment] 2015-12-28 04:51
Hm..yes, that is indeed a bug. Thanks for reporting it!

But as for your use case, I would recommend to create another component that "zip" together `mix.items` and individual `<g>` tags and yield each entry down. This would create unique instances for selection that'll run fine with `.scheduleOnce`

``` hbs
{{#arrangement-grid ...  as |select height width|}}
  {{#zip-entries select=select items=mix.items as |item g-tag|}}
    {{arrangement-grid/track-clip select=g-tag}}

    ...
  {{/zip-entries}}
{{/arrangement-grid}}
```

Here's the zip-entries component

``` javascript
Ember.Component.extend(GraphicSupport, {
  layout: hbs`
    {{#each entries as |entry|}}
      {{yield entry.item entry.tag}}
    {{/each}}
  `,

  select: null,

  items: null,
  tags: null,

  entries: Ember.computed('items', 'tags', function () {
    return d3.zip(this.get('items'), this.get('tags')).map(([ item, tag ]) => {
      return { item, tag };
    });
  }),

  call: join('items', '.item', {
    update(selection) {
      this.set('tags', selection);
    }
  })

});
```

**Comment by ming-codes** [comment] 2015-12-30 08:15
I gave this some more thought.

From the perspective of Ember, this does seems wrong because you're rendering multiples inside an `{{each}}` helper. But from the perspective of d3, this is expected behavior because you're trying to render into the same context element.

This can be handled in 2 ways. You can either create a helper "each" component like above, or make the child component to insert element on `.call`. I think the helper "each" is more of a robust solution.

**Comment by wolfbiter** [comment] 2016-01-28 04:49
@ming-codes 

So it took me several weeks of coming back and puzzling about this before I really understood your comment. Thanks for sharing, I feel like I understand d3 much better now.

i implemented `zip-entries`, and most things worked as you recommended. however, components with `GraphicSupport` expect `select` to be a `SelectionProxy`, and the `selection` passed to `join` is not a `SelectionProxy` but a d3 selection. so i had to update `zip-entries` to:

```
  call: join('items', '.item', {
    // 'selection' is a d3 selection, not an ember-cli-d3 selection
    update(selection) {
      // for each element, create a new ember-cli-d3 selection
      this.set('tags', selection[0].map((selection) => {
        return SelectionProxy.create({ element: selection }).get('select');
      }));
    }
  }),
```

**Comment by wolfbiter** [comment] 2016-01-28 04:50
^ works wonderfully, and i'm unblocked. i now have a zooming / panning SVG (using d3.zoom), with several track-clips drawn onto it!

**Comment by ming-codes** [comment] 2016-01-28 17:58
Great! :+1: I'll be closing this now.

**Closed as completed by ming-codes** 2016-01-28 17:58 UTC
Labels: bug

**Comment by wolfbiter** [comment] 2016-02-10 22:51
@ming-codes well the original issue is still technically valid. are you deciding that you dont want to support multiple renders of the same selection?

**Comment by ming-codes** [comment] 2016-02-10 23:28
That is correct. It wouldn't make sense from a D3 point of view. For your case, you can fold the `{{each}}` or `{{zip-entries}}` into `{{arrangement-grid}}` itself so you don't need a separate component.
