### ISSUE TITLE
Ember build fails on Windows when ember-cli-d3 included in app

### ISSUE THREAD

**Issue by staffe** [lightblade/ember-cli-d3#69] opened 2016-04-08 11:14 UTC
I have installed using `ember install ember-cli-d3` and run using `ember serve` having added the config to app.js

```
//app.js
import Ember from 'ember';
import Resolver from './resolver';
import loadInitializers from 'ember-load-initializers';
import config from './config/environment';

let App;

Ember.MODEL_FACTORY_INJECTIONS = true;

App = Ember.Application.extend({
    modulePrefix: config.modulePrefix,
    podModulePrefix: config.podModulePrefix,
    d3: {
        plugins: {
            'mbostock': [ 'sankey' ],
            'emeeks': [ 'adjacency-matrix' ]
        }
    },
    Resolver
});

loadInitializers(App, config.modulePrefix);

export default App;
```

I get the following error:

```
PS C:\Projects\graphdemo> ember serve
version: 2.4.2
Livereload server on http://localhost:49156
Serving on http://localhost:4200/
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, symlink 'C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\d3-plugi
ns-dist\dist\larskotthoff\chernoff\named-amd\main.js' -> 'C:\Projects\graphdemo\tmp\funnel-output_path-9Yk6ihj4.tmp\d3-p
lugins-dist\larskotthoff\chernoff\named-amd\main.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at symlinkWindows (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funnel\node_modules\symlink
-or-copy\index.js:90:16)
    at Function.symlinkOrCopySync [as sync] (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funne
l\node_modules\symlink-or-copy\index.js:56:5)
    at Funnel._copy (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funnel\index.js:398:19)
    at Funnel.processFile (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funnel\index.js:381:8)
    at Funnel.applyPatch [as _applyPatch] (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funnel\
index.js:298:12)
    at Funnel.<anonymous> (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funnel\index.js:250:10)

    at Array.forEach (native)
    at Funnel.processFilters (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funnel\index.js:249:
9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funnel\node_modules\broccoli
-plugin\index.js:7:31)
    at new Funnel (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funnel\index.js:44:10)
    at Funnel (C:\Projects\graphdemo\node_modules\ember-cli-d3\node_modules\broccoli-funnel\index.js:42:43)
    at Class.module.exports.treeForVendor (C:\Projects\graphdemo\node_modules\ember-cli-d3\index.js:36:43)
    at Class._treeFor (C:\Projects\graphdemo\node_modules\ember-cli\lib\models\addon.js:322:31)
    at Class.treeFor (C:\Projects\graphdemo\node_modules\ember-cli\lib\models\addon.js:290:19)
    at C:\Projects\graphdemo\node_modules\ember-cli\lib\broccoli\ember-app.js:446:20
    at Array.map (native)
    at EmberApp.addonTreesFor (C:\Projects\graphdemo\node_modules\ember-cli\lib\broccoli\ember-app.js:444:30)
    at EmberApp._processedVendorTree (C:\Projects\graphdemo\node_modules\ember-cli\lib\broccoli\ember-app.js:895:29)
```

**Comment by ming-codes** [comment] 2016-04-08 17:01
I see two separate things here.

### First

```
    d3: {
        plugins: {
            'mbostock': [ 'sankey' ],
            'emeeks': [ 'adjacency-matrix' ]
        }
    },
```

This block belongs in `ember-cli-build.js` in your project directory.

### Second

The funnel issue looks like a duplicate of #58

**Closed as completed** 2016-06-20 22:08 UTC
